### ISSUE TITLE
1.02버젼으로 백업시 백업한 작업물 에피소드 재생후에 모바마스 본섭으로 가게 됩니다.

### ISSUE THREAD

**Issue by tubame3** [redribbon0403/DereMemo#11]
https://tubame2.github.io/idolmaster/mypage/
https://github.com/tubame2/tubame2.github.io
-1.00버젼으로 백업한거

https://tubame3.github.io/idolmaster/mypage/
https://github.com/tubame3/tubame3.github.io
-1.02로 백업한거

뒤로가기 누르면 되어서 별 문제는 아닌데

백업과정에서 문제가 있었던건지 github으로 취합하는 과정에서 문제가 있었는지 모르겠네요.
혹시나 확인 가능할까요?

**Comment by redribbon0403** [comment]
[v0.1.3](https://github.com/redribbon0403/DereMemo/releases/tag/v0.1.3) 해결완료
